name: Check type hints

on:
  pull_request:
    branches:
      - master

jobs:
  mypy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v5
      - run: uv sync --group dev
      - run: uv run mypy --install-types --non-interactive --explicit-package-bases db_fwd.py tests/
